name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or master, depending on your default branch name

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run GitHub Pages deployment script
        run: |
          chmod +x ./deploy-gh-pages.sh
          ./deploy-gh-pages.sh
        env:
          CI: false  # Prevents the build from treating warnings as errors

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: gh-pages-build  # Uses our custom build folder
          branch: gh-pages
